<?xml version="1.0"?>
<package format="3">
  <name>seu_sentry_description</name>
  <version>0.1.0</version>
  <description>SEU four-module swerve sentry description for Gazebo Sim.</description>
  <maintainer email="TODO@example.com">SEU</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>pb2025_robot_description</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
