- ros_topic_name: /wheel/odometry
  gz_topic_name: /wheel/odometry
  ros_type_name: nav_msgs/msg/Odometry
  gz_type_name: gz.msgs.Odometry
  direction: GZ_TO_ROS

- ros_topic_name: /joint_states
  gz_topic_name: /world/default/model/sentry/joint_state
  ros_type_name: sensor_msgs/msg/JointState
  gz_type_name: gz.msgs.Model
  direction: GZ_TO_ROS

- ros_topic_name: /model/sentry/joint/gimbal_yaw_joint/cmd_vel
  gz_topic_name: /model/sentry/joint/gimbal_yaw_joint/cmd_vel
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ

- ros_topic_name: /swerve/front_left_steer_joint/cmd_pos
  gz_topic_name: /model/sentry/joint/front_left_steer_joint/0/cmd_pos
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ

- ros_topic_name: /swerve/front_right_steer_joint/cmd_pos
  gz_topic_name: /model/sentry/joint/front_right_steer_joint/0/cmd_pos
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ

- ros_topic_name: /swerve/rear_left_steer_joint/cmd_pos
  gz_topic_name: /model/sentry/joint/rear_left_steer_joint/0/cmd_pos
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ

- ros_topic_name: /swerve/rear_right_steer_joint/cmd_pos
  gz_topic_name: /model/sentry/joint/rear_right_steer_joint/0/cmd_pos
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ

- ros_topic_name: /swerve/front_left_wheel_joint/cmd_vel
  gz_topic_name: /model/sentry/joint/front_left_wheel_joint/cmd_vel
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ

- ros_topic_name: /swerve/front_right_wheel_joint/cmd_vel
  gz_topic_name: /model/sentry/joint/front_right_wheel_joint/cmd_vel
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ

- ros_topic_name: /swerve/rear_left_wheel_joint/cmd_vel
  gz_topic_name: /model/sentry/joint/rear_left_wheel_joint/cmd_vel
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ

- ros_topic_name: /swerve/rear_right_wheel_joint/cmd_vel
  gz_topic_name: /model/sentry/joint/rear_right_wheel_joint/cmd_vel
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
